yolo_args:
  data: /workspace/tsd/data/data.yaml
  imgsz: 64

data:
  train: /workspace/tsd/data/train/images
  val: /workspace/tsd/data/valid/images
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

model:
  nc: 15
  name: yolov8n.pt
  cfg: yolov8n.yaml

train:
  dataloader_num_wokers: 4
  batch_size: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  num_training_steps: 225
  accelerator: cpu
  precision: 32
  val_check_interval: 1.0
  gradient_clip_val: 3.0
  log_every_n_steps: 1

loss:
  cls: 0.5
  box: 7.5
  dfl: 1.5

artifacts:
  experiment_name: train-exp
  checkpoint:
    dirpath: checkpoints
    filename: "{epoch:02d}-{val_loss:.4f}"
    monitor: val_loss
    save_top_k: 1
    every_n_epochs: 1
  tracking_uri: http://0.0.0.0:5000
